### ISSUE TITLE
Filter issues

### ISSUE THREAD

**Issue by lazgeo** [TekniskSupport/home-assistant-resrobot#26]
Trying to use filters to get only specific trains doesn't seem to work, it returns all results, not just the ones in "must". My config is as follows.

```
- platform: resrobot
  key: !secret trafiklab_resrobot_api
  fetch_interval: 3
  departures:
    - stop_id: 740000260
      name: Tåg till Malmö - Resrobot
      max_journeys: 5
      sensors: 5
      unit: "🕑"
      time_format: "%H:%M"
      filter:
        - means_of_transport: 2
        - means_of_transport: 4
          type: "must"
          direction: "Malmö"
```
