### ISSUE TITLE
Feature request - Allow different filter types

### ISSUE THREAD

**Issue by TekniskSupport** [TekniskSupport/home-assistant-resrobot#9]
Allow for filter types for direction property

examples:
```yaml
filter:
   - line: 4
     direction: Centralstationen
     type: must_not
```

```yaml
filter:
   - line: 4
     direction: Centralstationen
     type: must
```

```yaml
filter:
   - line: 4
     direction: Central
     type: contains
```
